language: python
cache:
    pip: true

install:
  - pip install tox

script:
  - tox

matrix:
  include:
    - { python: 3.7-dev, env: TOXENV=py37 }
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }
    - { python: 3.6, env: TOXENV=black }
